# docker-compose file reference:
# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9"
services:
  web:
    build:
      context: .
      args:
        - DB_LOCATION=local
    ports:
      - "8082:80"
    depends_on:
      - db
    # Sensitive information is passed as environment variables in local
    # development. Although local development can directly use plain text in
    # code and cofigurations, these secrets are used to emulate production
    # environment, so that locally developed applications can be deployed more
    # straightforwardly.
    #
    # ../OpenPedCan-api-secrets directory is not in docker build context or
    # tracked by git repository.
    #
    # Environment file format reference:
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file
    env_file: ../OpenPedCan-api-secrets/access_db.env
  db:
    build:
      context: .
      shm_size: 2gb
      # postgres docker image has VOLUME /var/lib/postgresql/data. When running
      # without specifying any volume, docker will create an anonymous volume,
      # which is easier for cleaning up.
      #
      # docker-compose stopped containers and anonymous volume(s) can be cleaned
      # up by `docker-compose rm -fv`.
      #
      # "Warning: scripts in /docker-entrypoint-initdb.d are only run if you
      # start the container with a data directory that is empty; any
      # pre-existing database will be left untouched on container startup."
      #
      # Reference: https://hub.docker.com/_/postgres
      dockerfile: db/db.Dockerfile
    # postgres version 11 initdb sets password_encryption according to
    # authmethodlocal and authmethodhost
    #
    # Ref:
    # https://github.com/postgres/postgres/blob/REL_11_STABLE/src/bin/initdb/initdb.c#L1220-L1226
    #
    # load_db process is to run pg_restore on the output of build_db process.
    # The build_db process is completed by running db/build_db.sh.
    env_file: ../OpenPedCan-api-secrets/load_db.env
